#!/bin/zsh

system_type=$(uname -s)

# Here we make sure YADM & VSCode play nice by making sure '**' is in
# $GIT_DIR/info/exclude
yadm gitconfig advice.addIgnoredFile false
GIT_DIR=$HOME/.local/share/yadm/repo.git
grep "^\*\*$" $GIT_DIR/info/exclude > /dev/null
excluded=$?
if [[ $excluded -ne O ]]; then
  echo "**" >> $GIT_DIR/info/exclude
fi


if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  BREWFILE="${HOMEBREW_BUNDLE_FILE:-$HOME/.Brewfile}"
  if [ -f "$BREWFILE" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$BREWFILE"
  fi

fi

if [ "$system_type" = "Darwin" ]; then

  # possibly add something here to ensure iTerm2 is installed using Homebrew
  # cask like in the previous example

  if [ -d "$HOME/.config/iterm" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm"
  fi

fi

nvm install node

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:scamden/dotfiles.git"

