#!/bin/zsh

system_type=$(uname -s)

# Here we make sure YADM & VSCode play nice by making sure '**' is in
# $GIT_DIR/info/exclude.
yadm gitconfig advice.addIgnoredFile false
GIT_DIR="$HOME/.local/share/yadm/repo.git"
if [ -d "$GIT_DIR" ] && ! grep "^\*\*$" "$GIT_DIR/info/exclude" >/dev/null 2>&1; then
  echo "**" >> "$GIT_DIR/info/exclude"
fi


if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  BREWFILE="${HOMEBREW_BUNDLE_FILE:-$HOME/.Brewfile}"
  if [ -f "$BREWFILE" ]; then
    echo "Updating Homebrew bundle"
    brew bundle --file="$BREWFILE"
  fi

fi

if [ "$system_type" = "Darwin" ]; then

  # possibly add something here to ensure iTerm2 is installed using Homebrew
  # cask like in the previous example

  if [ -d "$HOME/.config/iterm" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm"
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
  fi

fi

if command -v mise >/dev/null 2>&1; then
  echo "Installing mise tools"
  mise install
else
  echo "mise is not installed; install it with Homebrew and rerun bootstrap" >&2
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:scamden/dotfiles.git"

